project: MR-training
group: MR
name: mr
hidden_dims: [256, 256]
orthogonal_init: false
activations: relu
activation_final: none
dataset_id: D4RL_antmaze-large-diverse-v2
dataset: ~/busy-beeway/transformers/ant_labels/antmaze-large-diverse-v2/antmaze-large-diverse-v2_pref.hdf5
training_reduce: 0.0
epochs: 10
batch_size: 256
lr: 0.0003
workers: 0
criteria_type: acc
criteria_key: training_acc
pin_memory: true
seed: 0
data_from_disk: false
checkpoints_path: ~/busy-beeway/transformers/ant_labels/antmaze-large-diverse-v2_models