project: PT-training
group: PT
name: pt
embd_dim: 256
pref_attn_embd_dim: null
num_heads: 4
attn_dropout: 0.1
resid_dropout: 0.1
intermediate_dim: null
num_layers: 1
embd_dropout: 0.1
model_eps: 0.1
max_ep_length: 200
default_max_pos: 2048
dataset_id: D4RL_pen-v2
dataset: ~/busy-beeway/transformers/pen_labels/AdroitHandPen-v1_pref_small.hdf5
training_reduce: 0.0
epochs: 10
batch_size: 16
initial_lr: 0.0001
peak_lr: 0.001
end_lr: 0.0001
warmup_steps: null
decay_steps: null
workers: 0
criteria_type: acc
criteria_key: training_acc
pin_memory: true
seed: 0
data_from_disk: false
checkpoints_path: ~/busy-beeway/transformers/pen_labels/pt_pen